### ISSUE TITLE
Open source checklist 📝

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#2197]
- [x] Port Zed over to GPUI2 (see replies below for screenshot updates)
- [x] Promote Zed Nightly to Zed Preview (read about it [here](https://zed.dev/blog/gpui-2-on-preview))
- [X] Extended preview period (download a copy [here](https://zed.dev/releases/preview))
- [x] Channels shipped to Zed Preview (read about it [here](https://zed.dev/blog/channels))
- [x] Code documentation
- [X] CONTRIBUTING.md guide
- [x] Promote Zed Preview to Zed Stable
- [x] Potential blog posts

*This list is a work in progress. Items may be added or removed over time.*

**Comment by JosephTLyons** [comment]
Update on the GPUI2 app port:

<img width="1608" alt="SCR-20231119-tlhv" src="https://github.com/zed-industries/community/assets/19867440/062a0041-1dd3-4912-b26c-e84628f4bb8e">

**Comment by JosephTLyons** [comment]
Update #2. Ignore the red boards around some buttons.

<img width="1608" alt="SCR-20231129-tavc" src="https://github.com/zed-industries/community/assets/19867440/7644a25f-ded7-4c31-8750-5042d8942969">

**Comment by JosephTLyons** [comment]
A couple of new screenshots of the progress (ignore the visual bugs)

<img width="1608" alt="SCR-20231213-osja" src="https://github.com/zed-industries/community/assets/19867440/6ede1ef3-7d76-4590-8698-b7f488ba3bde">

<img width="1608" alt="SCR-20231213-orzr" src="https://github.com/zed-industries/community/assets/19867440/bd578b55-af48-432d-979a-269bfc6f56c9">

**Comment by JosephTLyons** [comment]
<img width="1608" alt="SCR-20231220-cqru" src="https://github.com/zed-industries/community/assets/19867440/480b462f-faf6-4315-a3e7-ee109b4f4f74">

**Comment by JosephTLyons** [comment]
<img width="1608" alt="SCR-20231220-crqm" src="https://github.com/zed-industries/community/assets/19867440/e5807132-0e8e-404d-9087-b2f5a4896051">

**Comment by JosephTLyons** [comment]
The changes have been merged into preview. Blog post [here](https://zed.dev/blog/gpui-2-on-preview), release [here](https://zed.dev/releases/preview/0.119.0).

**Comment by trevyn** [comment]
Very excited about this. To clarify, is the plan to go open source shortly after preview is promoted to stable, or are the rest of the items on the checklist expected to take a significant amount of time?

**Comment by jangorecki** [comment]
Looking the checklist I don't see an open source OS support there. I wonder if that could be prioritized, so open source OS users could enjoy open source zed, rather than letting only closed source OS users enjoy open source zed.

**Comment by jakobkg** [comment]
@jangorecki that seems to be tracked separately in issue #174

**Comment by JosephTLyons** [comment]
> Very excited about this. To clarify, is the plan to go open source shortly after preview is promoted to stable, or are the rest of the items on the checklist expected to take a significant amount of time?

The plan is to finish off the checklist - that being said, this list is a little misleading, as a few of the unchecked items are being worked on at the same time and are almost done, so progress is going to jump really soon!

**Comment by trevyn** [comment]
What license do you plan to use?

**Comment by JosephTLyons** [comment]
The Zed codebase is now open sourced:

- [Repo](https://github.com/zed-industries/zed)
- [Blog post](https://zed.dev/blog/zed-is-now-open-source)
